-- Runs before the schema migration generated by `prisma migrate dev`.
-- Extensions + the human-friendly ticket number sequence (starts after the
-- seeded range 1013–1042 so dev numbers line up with the frontend data).

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SEQUENCE IF NOT EXISTS ticket_number_seq START WITH 1043;
