// AUTO-GENERATED by scripts/generate-icon-registry.mjs.
// Do not edit by hand. Re-run the script if brand SVGs change.

export const ICON_REGISTRY: Record<string, string> = {
  'action-archive': `<rect x="3" y="5" width="18" height="4" rx="1" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 5 9 L 5 19 Q 5 20 6 20 L 18 20 Q 19 20 19 19 L 19 9" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 10 13 L 14 13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'action-assign-me': `<circle cx="9" cy="8" r="3.5" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 3 19 Q 3 13 9 13 Q 13 13 14.5 16" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M 16 17 L 18 19 L 22 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'action-attach': `<path d="M 14 4 L 7 11 Q 5 13 7 15 Q 9 17 11 15 L 18 8 Q 21 5 18 2 Q 15 -1 12 2 L 5 9 Q 1 13 5 17 Q 9 21 13 17 L 19 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'action-convert': `<circle cx="7" cy="7" r="3" stroke="currentColor" stroke-width="1.5"/>
  <rect x="14" y="14" width="6" height="6" rx="1" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 9 10 Q 12 12, 13 14 M 11 14 L 13 14 L 13 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'action-copy-link': `<path d="M 11 6 L 9 4 Q 7 2 5 4 L 4 5 Q 2 7 4 9 L 6 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 13 18 L 15 20 Q 17 22 19 20 L 20 19 Q 22 17 20 15 L 18 13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <line x1="9" y1="15" x2="15" y2="9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'action-delete': `<path d="M 5 7 L 19 7 M 9 7 L 9 5 Q 9 4 10 4 L 14 4 Q 15 4 15 5 L 15 7 M 7 7 L 8 20 Q 8 21 9 21 L 15 21 Q 16 21 16 20 L 17 7" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 11 11 L 11 17 M 13 11 L 13 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-opacity="0.5"/>`,
  'action-duplicate': `<rect x="8" y="8" width="12" height="12" rx="2" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 16 8 L 16 6 Q 16 4 14 4 L 6 4 Q 4 4 4 6 L 4 14 Q 4 16 6 16 L 8 16" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'action-edit': `<path d="M 4 20 L 8 19 L 19 8 L 16 5 L 5 16 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 14 7 L 17 10" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'action-link': `<path d="M 10 14 Q 7 14 7 11 Q 7 8 10 8 L 12 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M 14 8 Q 17 8 17 11 Q 17 14 14 14 L 12 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="9" y1="11" x2="15" y2="11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'action-move': `<rect x="4" y="6" width="8" height="10" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
  <rect x="14" y="10" width="6" height="10" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 9 11 L 16 11 M 14 9 L 16 11 L 14 13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'action-unwatch': `<path d="M 4 8 Q 2 10 2 12 Q 7 19 12 19 Q 14 19 16 18.3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 9 6 Q 10.5 5 12 5 Q 17 5 22 12 Q 21 13.5 19.5 14.8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 9.5 9.5 Q 9 10.5 9 12 Q 9 15 12 15 Q 13.5 15 14.5 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="3" y1="3" x2="21" y2="21" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'action-watch': `<path d="M 2 12 Q 7 5 12 5 Q 17 5 22 12 Q 17 19 12 19 Q 7 19 2 12 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="1.5"/>`,
  'auth-key': `<circle cx="8" cy="14" r="4" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 11 12 L 21 6 M 18 8 L 19.5 9.5 M 15 10 L 16.5 11.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'auth-lock': `<rect x="5" y="11" width="14" height="10" rx="2" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 8 11 L 8 8 Q 8 4 12 4 Q 16 4 16 8 L 16 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="12" cy="15.5" r="1.2" fill="currentColor"/>
  <path d="M 12 16.5 L 12 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'auth-shield': `<path d="M 12 3 L 19 6 L 19 12 Q 19 17 12 21 Q 5 17 5 12 L 5 6 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'auth-sign-in': `<path d="M 13 4 L 19 4 Q 20 4 20 5 L 20 19 Q 20 20 19 20 L 13 20" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 4 12 L 14 12 M 10 8 L 14 12 L 10 16" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'auth-sign-out': `<path d="M 11 4 L 5 4 Q 4 4 4 5 L 4 19 Q 4 20 5 20 L 11 20" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 10 12 L 20 12 M 16 8 L 20 12 L 16 16" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'auth-unlock': `<rect x="5" y="11" width="14" height="10" rx="2" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 8 11 L 8 8 Q 8 4 12 4 Q 15 4 16 6.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="12" cy="15.5" r="1.2" fill="currentColor"/>
  <path d="M 12 16.5 L 12 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'comment-add': `<path d="M 4 11 Q 4 5 10 5 L 14 5 Q 20 5 20 11 Q 20 17 14 17 L 10 17 L 6 21 L 6 17 Q 4 17 4 11 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 12 9 L 12 13 M 10 11 L 14 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'comment-attach': `<path d="M 14 4 L 7 11 Q 5 13 7 15 Q 9 17 11 15 L 18 8 Q 21 5 18 2 Q 15 -1 12 2 L 5 9 Q 1 13 5 17 Q 9 21 13 17 L 19 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'comment-emoji': `<circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 8.5 14 Q 12 17 15.5 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <circle cx="9" cy="10" r="1" fill="currentColor"/>
  <circle cx="15" cy="10" r="1" fill="currentColor"/>`,
  'comment-mention': `<circle cx="12" cy="12" r="3.5" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 15.5 8.5 L 15.5 13 Q 15.5 14.5 17 14.5 Q 19 14.5 19 11 Q 19 5 12 5 Q 5 5 5 12 Q 5 19 12 19 Q 14 19 16 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'comment-reply': `<path d="M 9 7 L 4 12 L 9 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 4 12 L 14 12 Q 20 12 20 18 L 20 19" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'comment-send': `<path d="M 4 12 L 21 4 L 14 21 L 11 13 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 11 13 L 21 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'file-audio': `<path d="M 7 9 L 7 15 M 10 6 L 10 18 M 13 8 L 13 16 M 16 11 L 16 13 M 19 7 L 19 17" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>`,
  'file-download': `<path d="M 12 4 L 12 15 M 7 11 L 12 16 L 17 11" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 4 18 L 4 19 Q 4 20 5 20 L 19 20 Q 20 20 20 19 L 20 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'file-external': `<path d="M 18 4 L 11 11 M 18 4 L 18 9 M 18 4 L 13 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 14 6 L 6 6 Q 5 6 5 7 L 5 18 Q 5 19 6 19 L 17 19 Q 18 19 18 18 L 18 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'file-generic': `<path d="M 6 4 L 14 4 L 19 9 L 19 20 Q 19 21 18 21 L 6 21 Q 5 21 5 20 L 5 5 Q 5 4 6 4 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 14 4 L 14 9 L 19 9" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'file-image': `<rect x="4" y="5" width="16" height="14" rx="2" stroke="currentColor" stroke-width="1.5"/>
  <circle cx="9" cy="10" r="1.5" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 5 17 L 10 12 L 13 15 L 16 13 L 19 16" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round"/>`,
  'file-pdf': `<path d="M 6 4 L 14 4 L 19 9 L 19 20 Q 19 21 18 21 L 6 21 Q 5 21 5 20 L 5 5 Q 5 4 6 4 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 14 4 L 14 9 L 19 9" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <text x="12" y="17.5" text-anchor="middle" font-family="Inter, sans-serif" font-size="5.5" font-weight="600" fill="currentColor" letter-spacing="0.2">PDF</text>`,
  'file-upload': `<path d="M 12 16 L 12 5 M 7 10 L 12 5 L 17 10" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 4 18 L 4 19 Q 4 20 5 20 L 19 20 Q 20 20 20 19 L 20 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'file-video': `<rect x="4" y="5" width="16" height="14" rx="2" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 10 9 L 16 12 L 10 15 Z" fill="currentColor"/>`,
  'file-zip': `<path d="M 6 4 L 14 4 L 19 9 L 19 20 Q 19 21 18 21 L 6 21 Q 5 21 5 20 L 5 5 Q 5 4 6 4 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 14 4 L 14 9 L 19 9" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 11 5 L 11 7 M 11 9 L 11 11 M 11 13 L 11 15" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <rect x="9.5" y="15" width="3" height="3.5" rx="0.5" stroke="currentColor" stroke-width="1.5"/>`,
  'list-columns': `<rect x="4" y="4" width="16" height="16" rx="2" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 9 4 L 9 20 M 15 4 L 15 20" stroke="currentColor" stroke-width="1.5" stroke-opacity="0.5"/>
  <circle cx="9" cy="9" r="1.5" fill="#fff" stroke="currentColor" stroke-width="1.5"/>
  <circle cx="15" cy="14" r="1.5" fill="#fff" stroke="currentColor" stroke-width="1.5"/>`,
  'list-density': `<path d="M 4 7 L 20 7 M 4 12 L 20 12 M 4 17 L 20 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M 4 7 L 4 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-opacity="0.5"/>
  <path d="M 20 7 L 20 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-opacity="0.5"/>`,
  'list-expand': `<path d="M 7 9 L 12 4 L 17 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 7 15 L 12 20 L 17 15" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 4 12 L 20 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-opacity="0.4"/>`,
  'list-filter': `<path d="M 4 5 L 20 5 L 14 13 L 14 20 L 10 18 L 10 13 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'list-group': `<path d="M 5 5 L 11 5 L 11 19 L 5 19" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 13 9 L 19 9 M 13 12 L 19 12 M 13 15 L 19 15" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'list-show-hide': `<path d="M 2 12 Q 7 5 12 5 Q 17 5 22 12 Q 17 19 12 19 Q 7 19 2 12 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <circle cx="12" cy="12" r="3" fill="currentColor" fill-opacity="0.15" stroke="currentColor" stroke-width="1.5"/>`,
  'list-sort': `<path d="M 7 4 L 7 18 M 4 7 L 7 4 L 10 7" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 17 20 L 17 6 M 14 17 L 17 20 L 20 17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'list-view': `<rect x="4" y="4" width="7" height="7" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
  <rect x="13" y="4" width="7" height="7" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
  <rect x="4" y="13" width="7" height="7" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
  <rect x="13" y="13" width="7" height="7" rx="1.5" stroke="currentColor" stroke-width="1.5"/>`,
  'state-caret': `<path d="M 8 10 L 12 14 L 16 10 Z" fill="currentColor"/>`,
  'state-check': `<path d="M 5 12 L 10 17 L 19 7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>`,
  'state-chevron-down': `<path d="M 6 10 L 12 16 L 18 10" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'state-chevron-left': `<path d="M 14 6 L 8 12 L 14 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'state-chevron-right': `<path d="M 10 6 L 16 12 L 10 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'state-chevron-up': `<path d="M 6 14 L 12 8 L 18 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'state-close': `<path d="M 6 6 L 18 18 M 18 6 L 6 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'state-critical': `<path d="M 8 3 L 16 3 L 21 8 L 21 16 L 16 21 L 8 21 L 3 16 L 3 8 Z" fill="#FFD4B8" stroke="var(--plumo-on-surface)" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 12 8 L 12 13" stroke="var(--plumo-on-surface)" stroke-width="1.8" stroke-linecap="round"/>
  <circle cx="12" cy="16" r="1" fill="var(--plumo-on-surface)"/>`,
  'state-help': `<circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 9.5 9.5 Q 9.5 7.5 12 7.5 Q 14.5 7.5 14.5 9.5 Q 14.5 11 12 12 L 12 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <circle cx="12" cy="17" r="1" fill="currentColor"/>`,
  'state-info': `<circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 12 11 L 12 16" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <circle cx="12" cy="8" r="1" fill="currentColor"/>`,
  'state-minus': `<path d="M 6 12 L 18 12" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>`,
  'state-warning': `<path d="M 12 4 L 21 19 L 3 19 Z" fill="#FFE8A3" stroke="var(--plumo-on-surface)" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 12 10 L 12 14" stroke="var(--plumo-on-surface)" stroke-width="1.5" stroke-linecap="round"/>
  <circle cx="12" cy="16.5" r="0.9" fill="var(--plumo-on-surface)"/>`,
  'time-log': `<path d="M 19 12 Q 19 5 12 5 Q 5 5 5 12 Q 5 19 12 19 Q 14 19 15.5 18.3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M 12 8 L 12 12 L 15 13.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 19 16 L 19 22 M 16 19 L 22 19" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'time-pause': `<rect x="7" y="5" width="3.5" height="14" rx="1" stroke="currentColor" stroke-width="1.5"/>
  <rect x="13.5" y="5" width="3.5" height="14" rx="1" stroke="currentColor" stroke-width="1.5"/>`,
  'time-play': `<path d="M 8 5 L 19 12 L 8 19 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'time-stop': `<rect x="6" y="6" width="12" height="12" rx="2" stroke="currentColor" stroke-width="1.5"/>`,
  'time-timer': `<circle cx="12" cy="13" r="7.5" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 12 9 L 12 13 L 15 14.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M 10 3 L 14 3 M 12 3 L 12 5.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'workspace-archive': `<rect x="3" y="6" width="18" height="4" rx="1" stroke="currentColor" stroke-width="1.5"/>
  <path d="M 5 10 L 5 18 Q 5 19 6 19 L 18 19 Q 19 19 19 18 L 19 10" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 9 13 L 15 13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M 8 4 L 8 6 M 16 4 L 16 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-opacity="0.5"/>`,
  'workspace-building': `<path d="M 4 20 L 20 20 M 5 20 L 5 7 Q 5 6 6 6 L 13 6 Q 14 6 14 7 L 14 20 M 14 11 L 19 11 Q 20 11 20 12 L 20 20" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round"/>
  <path d="M 8 10 L 8 11 M 11 10 L 11 11 M 8 14 L 8 15 M 11 14 L 11 15" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M 16.5 14 L 16.5 15 M 16.5 17 L 16.5 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'workspace-folder': `<path d="M 4 7 Q 4 6 5 6 L 9 6 L 11 8 L 19 8 Q 20 8 20 9 L 20 18 Q 20 19 19 19 L 5 19 Q 4 19 4 18 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'workspace-folder-open': `<path d="M 4 8 Q 4 7 5 7 L 9 7 L 11 9 L 18 9 Q 19 9 19 10 L 19 11" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 4 8 L 4 18 Q 4 19 5 19 L 19 19 L 21.5 11 Q 21.5 11 20.5 11 L 6 11 Q 5 11 4.5 12.5 L 4 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>`,
  'workspace-pin': `<path d="M 12 3 L 16 7 L 14 9 L 16 14 L 8 14 L 10 9 L 8 7 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
  <path d="M 12 14 L 12 21" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>`,
  'workspace-star': `<path d="M 12 4 L 14.5 9.5 L 20.5 10.3 L 16 14.4 L 17.3 20.3 L 12 17.3 L 6.7 20.3 L 8 14.4 L 3.5 10.3 L 9.5 9.5 Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>`,
  'workspace-star-filled': `<path d="M 12 4 L 14.5 9.5 L 20.5 10.3 L 16 14.4 L 17.3 20.3 L 12 17.3 L 6.7 20.3 L 8 14.4 L 3.5 10.3 L 9.5 9.5 Z" fill="#FFE8A3" stroke="#1E3A8A" stroke-width="1.5" stroke-linejoin="round"/>`,
};

export type IconName = keyof typeof ICON_REGISTRY;
